stages:
- prepare
- build

default:
  image: ubuntu:22.04@sha256:20fa2d7bb4de7723f542be5923b06c4d704370f0390e4ae9e1c833c8785644c1

collect:
  stage: prepare
  script:
  - bash generate.sh
  artifacts:
    expire_in: 1 day
    paths:
    - jobs.yml

dynamic:
  stage: build
  trigger:
    include:
      - artifact: jobs.yml
        job: collect
    strategy: depend
