stages:
- prepare
- build

default:
  image: ubuntu:21.04@sha256:26cd4ff32a9c031eaca3d6f589a7799f28b34a539e1bd81acbf1a6efeec4b1ce

collect:
  stage: prepare
  script:
  - bash generate.sh
  artifacts:
    expire_in: 1 day
    paths:
    - jobs.yml

dynamic:
  stage: build
  trigger:
    include:
      - artifact: jobs.yml
        job: collect
    strategy: depend
