stages:
- prepare
- build

default:
  image: ubuntu:22.04@sha256:2a7dffab37165e8b4f206f61cfd984f8bb279843b070217f6ad310c9c31c9c7c

collect:
  stage: prepare
  script:
  - bash generate.sh
  artifacts:
    expire_in: 1 day
    paths:
    - jobs.yml

dynamic:
  stage: build
  trigger:
    include:
      - artifact: jobs.yml
        job: collect
    strategy: depend
