stages:
- prepare
- build

default:
  image: ubuntu:22.04@sha256:26c68657ccce2cb0a31b330cb0be2b5e108d467f641c62e13ab40cbec258c68d

collect:
  stage: prepare
  script:
  - bash generate.sh
  artifacts:
    expire_in: 1 day
    paths:
    - jobs.yml

dynamic:
  stage: build
  trigger:
    include:
      - artifact: jobs.yml
        job: collect
    strategy: depend
