name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # renovate: tag=v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1

    - name: Login to DockerHub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # renovate: tag=v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build helpers image
      uses: docker/bake-action@master
      with:
        targets: helpers
        push: true

    - name: Build tools
      uses: docker/bake-action@master
      with:
        push: ${{ github.event_name != 'pull_request' }}

    - name: Build final image
      uses: docker/bake-action@master
      with:
        targets: example
        push: ${{ github.event_name != 'pull_request' }}
